### ISSUE TITLE
Home Couldn't connect to this accessory

### ISSUE THREAD

**Issue by dobrynski** [olivierguerriat/hassio-addons#1]
I can install and start the home bridge add-on but when I try to add the accessory to home I get the following error:
```
Couldn't add Home Assistant
Home Couldn't connect to this accessory.
```
The logs don't show any indication of a connection attempt that I can see, but upon container startup I do notice this warning:
```
Launching DBUS daemon…
Launching avahi daemon…
Process 22 died: No such process; trying to remove PID file. (/var/run/avahi-daemon//pid)
Launching homebridge…
```
I get the same error on my iPhone and my iPad.

Any ideas as to what could be causing it and/or how to fix the problem?
Thanks in advance.

Regards,
Michal

**Comment by olivierguerriat** [comment]
Do you have `[…] Homebridge is running on port 51826.` in your logs? If so, the warnings you have before (including the one you mention) are "expected" and shouldn't have consequences.

I believe your problem isn't directly due to this add-on but to your network setup, homebridge or HomeKit itself. I may be wrong, though.

* Is your home assistant installation on the same network (and subnet) as your iPhone? (seems like it since it detected it, but just to make sure)
* Did you try the two methods suggested by [the homebridge documentation under the "My iOS App Can't Find Homebridge" header](https://github.com/nfarina/homebridge#my-ios-app-cant-find-homebridge)? I found them very useful. You can find the homebridge config folder in `/config/homebridge/`, [as explained in the add-on documentation](https://github.com/olivierguerriat/hassio-addons/tree/master/homebridge).

If none of that work, please post the full log from `Launching homebridge…` up to the moment the Home app says it can't connect.

**Comment by dobrynski** [comment]
Well it's running in HASS.IO so it's not DIRECTLY on the same subnet as anything. But it is available on 192.168.1.64 which is on my main network.

I tried both solutions but neither worked.

I deleted the persist directory and readied. A new persist directory was created.

I changed the username and restarted the home bridge add-on. Same problem.

How can I get the entire log? I have so many sensors and devices that things scroll WAY past the Launching home bridge LONG before I can do anything and the log file is so large that even hastebin won't let me post it :/

EDIT: 4179 lines long to be specific.

**Comment by dobrynski** [comment]
OK.. I think I slimmed it down correctly:

https://hastebin.com/osupufaroz.coffeescript

**Comment by olivierguerriat** [comment]
Yes, I was indeed talking about hass.io itself (the homebridge add-on uses the host network).

You can access logs directly from docker by following [the debugging instructions of the hassio documentation](https://home-assistant.io/hassio/debugging/) and using `docker logs -f addon_***_homebridge` (use `docker ps` to get the exact container name).

I think your setup fails because you have more than 100 accessories, which is a hard limit imposed by HomeKit ([see this issue](https://github.com/nfarina/homebridge/issues/827#issuecomment-251146385)).

This add-on doesn't support multiple homebridge installations (and probably won't anytime soon, to be honest), but you can disable some accessories by using `homebridge_hidden: true` in your `customise` settings, [as explained here](https://github.com/home-assistant/homebridge-homeassistant#customization).

**Comment by dobrynski** [comment]
Ahh.. This may indeed be the problem..

Do you know if there is any way to get a count of the number of "accessories" you have? Maybe using the home assistant template tester?

**Comment by olivierguerriat** [comment]
I don't know for sure, but I think you can infer it from the logs by counting the `[HomeAssistant] Initializing platform accessory` lines (I count 110 of them in the log you posted).

Another way to reduce the number of accessories would be to remove one or more types (like "climate" or "media_player") altogether via the `supported_types` config of [homebridge-homeassistant](https://github.com/home-assistant/homebridge-homeassistant#configuration).

**Comment by dobrynski** [comment]
Any chance we could have the number of homebridge instances controlled via the options in the webui?

It appears as if you could simply run them all in the same container with pointers to different config/persist. Then all that would be necessary would be for the user to configure the supported devices in each instance so that you distribute the load.

**Comment by michaelyasay** [comment]
Has anyone tested it on iOS 10.3.3? I can't seems to add the homebridge in Home app.

**Comment by Freland** [comment]
@michaelyasay  I also have problems finding homebridge with iOS 10.3.3, has anyone got it to work with the latest iOS-update?

**Comment by dobrynski** [comment]
I'm still on 10.3.2 and I have these problems.. Even when I have only 1 device that is visible to homebridge.

**Comment by olivierguerriat** [comment]
This add-on is deprecated and doesn't work anymore.

Please uninstall it [and use Franck Nijhof's add-on instead](https://github.com/hassio-addons/repository/tree/master/homebridge). Your configuration should be transferred transparently.
